### ISSUE TITLE
发啥都报这个错

### ISSUE THREAD

**Issue by balh55y** [CMHopeSunshine/nonebot-plugin-learning-chat#12]
![image](https://user-images.githubusercontent.com/85926883/211383352-7f72eb88-8020-4cd7-9b95-12bd90f3f9db.png)

**Comment by NealScx** [comment]
> ![image](https://user-images.githubusercontent.com/85926883/211383352-7f72eb88-8020-4cd7-9b95-12bd90f3f9db.png)

请问怎么解决的呀~
