### ISSUE TITLE
聊天中接收到关闭指令后无法再通过指令开启

### ISSUE THREAD

**Issue by 296282349** [CMHopeSunshine/nonebot-plugin-learning-chat#13]
在QQ聊天中，发送“@bot 关闭学习\别学\闭嘴”这类指令，可以使机器人停止学习，并且机器人会回复语句表示不再学习。
但是如果再次发送“@bot 开启学习\学说话\快学”这类指令，机器人不会做出任何反应，也不会回复语句表示是否继续学习。
如果在停止学习前要求学习，机器人会回复语句说会进行学习。
只能通过手动通过yml文件或者web ui对配置文件内对应部分改回true才能重新打开学习功能。

**Comment by CMHopeSunshine** [comment]
已在`0.1.5`版本修复

**Comment by 296282349** [comment]
本人有事，请稍后再来
