### ISSUE TITLE
@bot 不可以的功能个别管理无法使用

### ISSUE THREAD

**Issue by TNTobsidian** [CMHopeSunshine/nonebot-plugin-learning-chat#14]
如题，回复消息，艾特bot，说不可以，有一个管理员无法使用，但是同群其他管理员可以正常使用，我个人也无法复现。但是对于这一个无法让bot不可以 的管理员，他确实次次回复，机器人都次次不理他（？）截图如下
![20CCAEE0-2681-407A-A31B-76FAF4E487C7](https://user-images.githubusercontent.com/65720409/211966084-bd06809a-8813-4536-8cc0-412a712dbe4e.jpeg)
![8C348463-46FC-45BD-9C2C-A29DB34B212C](https://user-images.githubusercontent.com/65720409/211966095-b5bc4121-b4c9-49e8-86aa-0c8c42f19118.jpeg)
![5335377D-CF2C-492B-8987-F4EB7938C24A](https://user-images.githubusercontent.com/65720409/211966639-e901b5be-7aee-49e1-be64-6b97a87d7037.jpeg)

**Comment by CMHopeSunshine** [comment]
这个管理是新设置的吗，可能是go-cqhttp的缓存还没更新

**Comment by TNTobsidian** [comment]
> 这个管理是新设置的吗，可能是go-cqhttp的缓存还没更新

可能，因为他说之后过了几个小时就好了😂
