### ISSUE TITLE
从未触发过主动发言

### ISSUE THREAD

**Issue by YaoKong** [CMHopeSunshine/nonebot-plugin-learning-chat#15]
我把主动发言阈值和间隔调到最低，连续发言调到100%都没有触发

**Comment by YaoKong** [comment]
现在连续主动发言概率失效了，调成0都会连续发言。是不是改成random.random() >=  config.speak_continuously_probability时直接break比较好，免得会一直循环到len(speak_list) >= config.speak_continuously_max_len

**Comment by CMHopeSunshine** [comment]
确实...写错了
