### ISSUE TITLE
跟“真寻bot”似乎有冲突

### ISSUE THREAD

**Issue by huihuiismywife** [CMHopeSunshine/nonebot-plugin-learning-chat#17]
安装了2.0版本后，真寻bot的相关功能就用不了了，但从第三方安装过来的其他功能还能正常使用
不太清楚是哪里有问题_(:з」∠)_

之前用1.1版本还是1.3版本来着的时候与真寻bot没有冲突，可以正常学习指令，web后台什么的也能使用，就是主动发言不太行（现在好像已经解决了）

**Comment by CMHopeSunshine** [comment]
提供一下报错日志

**Comment by CMHopeSunshine** [comment]
提供一下报错日志

**Comment by huihuiismywife** [comment]
[error_2023-01-17.log](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/files/10433256/error_2023-01-17.log)
是这个吗？第一次看这种东西 _(:з」∠)_

**Comment by huihuiismywife** [comment]
2.0版本是中午1点多添加到bot里的，然后功能就有的不能使用了，能使用的几个功能指令我在一开始就添加到了“全局屏蔽词”里了，那些没有添加进去的指令就用不了。临时添加到“屏蔽词”之后再使用也不行

**Comment by CMHopeSunshine** [comment]
日志里有三个报错，有一个是本插件的，是代码上有点问题，稍候会修，另外两个是`extensive_plugin\genshin_role_info`这个插件的问题，并非冲突导致的

**Comment by huihuiismywife** [comment]
新年快乐，还有辛苦了∠(°ゝ°)

**Comment by CMHopeSunshine** [comment]
新年快乐，昨天的0.2.1已修复，忘记说了

**Comment by huihuiismywife** [comment]
我又回来了，之前用的是1.0版本，直到升级到使用数据库的版本后就无法正常使用真寻bot的功能了。。。。
这边就是想说能不能搞个无数据库的高版本呢。。
如果嫌麻烦的话也可以无视咱这条信息(•́ω•̀ ٥)

**Comment by CMHopeSunshine** [comment]
啊哈？我这个插件没有过1.0版本额，一直都是用的数据库，是不是记混了）

**Comment by huihuiismywife** [comment]
不会呀，我用pip安装选版本的时候确实有0.1.0版本来着
一直到我更新之后才在bot启动界面有显示“[数据库]已启动”之类的提示

**Comment by CMHopeSunshine** [comment]
提示是后来加的

**Comment by huihuiismywife** [comment]
好叭，那打扰了(ᇂ_ᇂ|||)

**Comment by maoxig** [comment]
可能是版本更新后大佬加了个
if '' in COMMAND_START:
    COMMAND_START.remove('')，
你可以检查一下你COMMAND_START是不是除了这个就没有别的了？或者试一试在指令面前加"/"来触发

**Comment by huihuiismywife** [comment]
原来如此，咱把这条代码删了就能用了(滑稽.jpg)
就是得慢慢把常用指令添加到学习黑名单里_(:з」∠)_

**Comment by huihuiismywife** [comment]
我又又回来了，更新到最新版本`0.2.1`后把上边提到的这个指令删掉后可以正常工作了，但是WebUI界面打不开，退回到`0.2.0`版本后又可以正常打开了_(:з」∠)_

**Comment by huihuiismywife** [comment]
我又又回来了，更新到最新版本`0.2.1`后把上边提到的这个指令删掉后可以正常工作了，但是WebUI界面打不开，退回到`0.2.0`版本后又可以正常打开了_(:з」∠)_

**Comment by huihuiismywife** [comment]
我又又回来了，更新到最新版本`0.2.1`后把上边提到的这个指令删掉后可以正常工作了，但是WebUI界面打不开，退回到`0.2.0`版本后又可以正常打开了_(:з」∠)_

**Comment by maoxig** [comment]
如果你只是删掉了上面那条代码，那群友说的话应该都会判定不学习（后台应该能看到相关代码如下）,实际上你要是看到#2，就知道为什么会这样了。
elif COMMAND_START and self.data.message.startswith(tuple(COMMAND_START)):
            # 以命令前缀开头的消息，跳过
            log_debug('群聊学习', '➤该消息以命令前缀开头，跳过')
            return Result.Pass

**Comment by huihuiismywife** [comment]
还真是（头秃.jpg）
我还是继续用`0.1.0`版本的吧

**Comment by EightEggs** [comment]
我也遇到这个问题了。真寻bot里，这个插件似乎没“正确地”起作用。Web管理界面能看到数据库有数据，看起来都正常，但在命令行输出里都没有event matcher，只有bot启动和退出时有数据库连接和断开的info，也就是说它只能看着群友聊天，不能做出响应。

**Comment by huihuiismywife** [comment]
我现在的解决办法就是用`0.1.0`版本的，虽然主动发言有bug来着 _(:з」∠)_，外加要自己把一些指令加到黑名单里，其他方面还好说

**Comment by CMHopeSunshine** [comment]
> 我也遇到这个问题了。真寻bot里，这个插件似乎没“正确地”起作用。Web管理界面能看到数据库有数据，看起来都正常，但在命令行输出里都没有event matcher，只有bot启动和退出时有数据库连接和断开的info，也就是说它只能看着群友聊天，不能做出响应。@CMHopeSunshine

有数据说明是在正常工作，还没学到位而已，只有bot学习好且准备发言了，日志才会有event matcher显示

**Comment by EightEggs** [comment]
> 我现在的解决办法就是用`0.1.0`版本的，虽然主动发言有bug来着 _(:з」∠)_，外加要自己把一些指令加到黑名单里，其他方面还好说

maoxig说的跳过命令的那些代码我都删了，也没解决问题

**Comment by EightEggs** [comment]
> > 我也遇到这个问题了。真寻bot里，这个插件似乎没“正确地”起作用。Web管理界面能看到数据库有数据，看起来都正常，但在命令行输出里都没有event matcher，只有bot启动和退出时有数据库连接和断开的info，也就是说它只能看着群友聊天，不能做出响应。@CMHopeSunshine
> 
> 有数据说明是在正常工作，还没学到位而已，只有bot学习好且准备发言了，日志才会有event matcher显示

所以说我对着一个正常工作的插件de了一整天的bug🙃

**Comment by CCYellowStar** [comment]
现在真寻换了orm，是真的不能用了，一用真寻之前的一堆数据全炸 全变成sqlite3.OperationalError: no such table:

**Comment by CCYellowStar** [comment]
然后我把from tortoise.models import Model换成真寻的from services.db_context import Model，把这个插件的数据库启动关闭拿掉就可以用了，相当于和真寻共用数据库

**Comment by huihuiismywife** [comment]
作者大大额滴超人（膜拜.jpg）
![28403826d1faa15c_edit_272430203672492](https://user-images.githubusercontent.com/107234845/222188040-e3f494e3-26d7-4387-a0cb-d877b072f9aa.jpg)

**Comment by PackageInstaller** [comment]
> 然后我把from tortoise.models import Model换成真寻的from services.db_context import Model，把这个插件的数据库启动关闭拿掉就可以用了，相当于和真寻共用数据库

大佬，我修改了models.py中的tortoise.exceptions.OperationalError: no such table成from services.db_context import Model后还是一堆tortoise.exceptions.OperationalError: no such table的报错，是我没改完吗

**Comment by OrphanFaker** [comment]
> 

大佬，我和上面的一样，修改了models.py里面的也是报错no such table

**Comment by CCYellowStar** [comment]
> > 然后我把from tortoise.models import Model换成真寻的from services.db_context import Model，把这个插件的数据库启动关闭拿掉就可以用了，相当于和真寻共用数据库
> 
> 大佬，我修改了models.py中的from tortoise.models import Model換成from services.db_context import Model后还是一堆tortoise.exceptions.OperationalError: no such table的报错，是我没改完吗

还要把连接数据库和断开数据库的代码拿掉

**Comment by PackageInstaller** [comment]
> > > 然后我把from tortoise.models import Model换成真寻的from services.db_context import Model，把这个插件的数据库启动关闭拿掉就可以用了，相当于和真寻共用数据库
> > 
> > 
> > 大佬，我修改了models.py中的from tortoise.models import Model換成from services.db_context import Model后还是一堆tortoise.exceptions.OperationalError: no such table的报错，是我没改完吗
> 
> 还要把连接数据库和断开数据库的代码拿掉
大佬能向详细地指出还有哪里需要改吗，我菜，真不知道还有哪里要改，提前拜谢了

**Comment by CCYellowStar** [comment]
> > > > 然后我把from tortoise.models import Model换成真寻的from services.db_context import Model，把这个插件的数据库启动关闭拿掉就可以用了，相当于和真寻共用数据库
> > > 
> > > 
> > > 大佬，我修改了models.py中的from tortoise.models import Model換成from services.db_context import Model后还是一堆tortoise.exceptions.OperationalError: no such table的报错，是我没改完吗
> > 
> > 
> > 还要把连接数据库和断开数据库的代码拿掉
> > 大佬能向详细地指出还有哪里需要改吗，我菜，真不知道还有哪里要改，提前拜谢了

![image](https://user-images.githubusercontent.com/47291058/229274929-89f90790-1729-459a-bcda-84ddde0a2d47.png)
