### ISSUE TITLE
学习优化建议

### ISSUE THREAD

**Issue by moyuguguji** [CMHopeSunshine/nonebot-plugin-learning-chat#2]
请问一下能不能就是聊天记录触发其他插件指令不学习呀，bot指令记录学习有点太混乱了，黑名单加不完，而且会影响点正常对话学习
![QQ截图20230107083120](https://user-images.githubusercontent.com/108826874/211122020-192fed85-63dd-4185-9567-f337bdd674bc.png)
而且这个除指令外好像还是会记录唉，还是说只不记录这个插件的指令），求优化qwq

**Comment by CMHopeSunshine** [comment]
如果其他插件的指令在运行后没有进行block，让它向下传递的话，插件没办法判断到它是否是指令，所以依旧会记录，我目前能想到的是让本插件不学习以`命令前缀`开头的聊天记录了，下版本加。
