### ISSUE TITLE
插件会阻断其他插件指令的正常触发

### ISSUE THREAD

**Issue by Yunmo-1** [CMHopeSunshine/nonebot-plugin-learning-chat#23]
![image](https://user-images.githubusercontent.com/79674967/218244902-f59e378b-3c8b-4178-a019-a286c33fa6a4.png)
这个要怎么配置

**Comment by Yunmo-1** [comment]
感觉是你这个插件的问题

**Comment by Yunmo-1** [comment]
才加这个插件时其他插件的指令可以正常运行，后面就不行了

**Comment by CMHopeSunshine** [comment]
不是本插件
https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/blob/1c9d2ed9895311b1ee1c370d2a6e3d5fc5bb87e3/nonebot_plugin_learning_chat/__init__.py#L37
`block=False`
看你的日志也能看得出是`src.插件.复读姬`阻断的

**Comment by Yunmo-1** [comment]
嗯，不是所有指令都无法使用。。

**Comment by cpuopt** [comment]
[https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/blob/master/nonebot_plugin_learning_chat/config.py#L24](url)
应该是这个原因

**Comment by NanakoOfficial** [comment]
> [https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/blob/master/nonebot_plugin_learning_chat/config.py#L24](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/blob/master/nonebot_plugin_learning_chat/config.py#L24)
> 应该是这个原因

大佬，把这段删掉就可以了吗

**Comment by cpuopt** [comment]
> 
> > [https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/blob/master/nonebot_plugin_learning_chat/config.py#L24](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/blob/master/nonebot_plugin_learning_chat/config.py#L24)
> > 应该是这个原因
> 
> 大佬，把这段删掉就可以了吗

作者在
https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/commit/605e8c6db1a0ab69a7697e20a8252e119ec7d9ee
已经修复了这个问题
