### ISSUE TITLE
在更改nonebot端口后，无法访问网络管理页面。

### ISSUE THREAD

**Issue by fatinghenji** [CMHopeSunshine/nonebot-plugin-learning-chat#24]
由于端口冲突，我将nonebot的监听端口从8080改成了8069
之后就无法访问管理页面了，访问返回：`{"detail":"Not Found"}`
请问该问题应该如何解决。

**Comment by CMHopeSunshine** [comment]
管理页面的端口是跟随nonebot的端口的，请确认是否访问了正确端口

**Comment by fatinghenji** [comment]
> 管理页面的端口是跟随nonebot的端口的，请确认是否访问了正确端口

`.env.prod`文件中相关配置项
```
HOST=0.0.0.0                                         
PORT=8069
```
应该不是访问端口的问题叭

**Comment by CMHopeSunshine** [comment]
那你管理页面是访问的哪个端口

**Comment by CMHopeSunshine** [comment]
是http://127.0.0.1:8069/LittlePaimon/admin/ 吗

**Comment by fatinghenji** [comment]
http://192.168.123.146:8069/LittlePaimon/admin/
我是在局域网的另一个终端上访问的

**Comment by CMHopeSunshine** [comment]
那页面提示什么，是`无法访问此网站`还是`not found`

**Comment by fatinghenji** [comment]
{"detail":"Not Found"}

**Comment by CMHopeSunshine** [comment]
之前地址说错了，应该是`ip地址:端口号/learning_chat/`

**Comment by fatinghenji** [comment]
更换网址后访问控制台成功
