### ISSUE TITLE
上下文的联想和长期记忆如何？

### ISSUE THREAD

**Issue by hezi2020** [CMHopeSunshine/nonebot-plugin-learning-chat#26]

**Comment by CMHopeSunshine** [comment]
能具体描述一下吗，没太听懂）

**Comment by hezi2020** [comment]
准备入nonebot坑，见到此插件，非常欣喜，但在本插件和另外的牛牛插件之间犯了难，不知道该如何选择，不知道在学习和发送上是参考当前聊天群聊的上下文多轮对话进行学习和发送还是什么，每一个聊天的个体信息短期会存储吗？

**Comment by CMHopeSunshine** [comment]
是的，根据上下文多轮对话进行发送，会将收到的所有聊天记录都保存在数据库中。
如果你说的牛牛是指[Pallas-Bot](https://github.com/MistEO/Pallas-Bot)的话，本插件就是根据牛牛改编的，将牛牛使用的mongodb改为了sqlite，以及算法上小改动，基本上差别不大。

**Comment by CMHopeSunshine** [comment]
是的，根据上下文多轮对话进行发送，会将收到的所有聊天记录都保存在数据库中。
如果你说的牛牛是指[Pallas-Bot](https://github.com/MistEO/Pallas-Bot)的话，本插件就是根据牛牛改编的，将牛牛使用的mongodb改为了sqlite，以及算法上小改动，基本上差别不大。

**Comment by hezi2020** [comment]
了解了，谢谢答疑
