### ISSUE TITLE
插件配置问题

### ISSUE THREAD

**Issue by Arturia169** [CMHopeSunshine/nonebot-plugin-learning-chat#29]
我使用虚拟环境安装插件后 插件的目录是这样的
![image](https://user-images.githubusercontent.com/69199123/229338848-8984ee6c-fb65-4df4-8b19-a8d416561b00.png)
没有找到**learning_chat.yml**文件来更改配置

这是插件路径".venv/lib/python3.9/site-packages/nonebot_plugin_learning_chat"

**Comment by CMHopeSunshine** [comment]
不在插件路径，在nb目录里
