### ISSUE TITLE
【bug】win端访问web失败404

### ISSUE THREAD

**Issue by Agnes4m** [CMHopeSunshine/nonebot-plugin-learning-chat#31]
- server: win2012
- nb:2.0.0rc4
- py:3.9.12
- 安装方式：nb plugin install xx
- env：
```
HOST=0.0.0.0
PORT=29212
```
- nb端输出
![image](https://user-images.githubusercontent.com/70925546/233793044-85e730c7-c11f-4fe5-81d7-a7168874ce82.png)
- web输出
- 
![image](https://user-images.githubusercontent.com/70925546/233793232-f37624f8-ed04-4ee8-8292-49c70aa9e66e.png)

**Comment by CMHopeSunshine** [comment]
请确保你已正确加载本插件，并在本插件的配置中开启了`enable_web`选项

**Comment by Agnes4m** [comment]
我确保插件成功加载，并且配置已开启
![image](https://user-images.githubusercontent.com/70925546/233925431-5231ac37-e1d4-4d56-9b7e-4240a00bcea4.png)

但是我注意到，收集聊天信息会出现以下报错，每一句都触发，同时web端无法访问
![image](https://user-images.githubusercontent.com/70925546/233926445-02bbc0da-ef8a-486d-97fd-d152a8b15e5f.png)
![image](https://user-images.githubusercontent.com/70925546/233926544-0eb18a89-8380-41f7-89b4-5af6beb74ac7.png)

**Comment by Agnes4m** [comment]
即使在加载插件只有本插件和定时插件的情况下，仍然是这种报错
![image](https://user-images.githubusercontent.com/70925546/233932916-c586e626-9714-480f-ac70-fef36c58c79c.png)

**Comment by CMHopeSunshine** [comment]
我大概知道问题了，将fastapi升级到最新版，(进入虚拟环境)`pip install fastapi`
由于nonebot2 rc4版本修改了启动钩子函数，需要把fastapi升到0.93.0以上版本才能运行启动钩子

**Comment by Agnes4m** [comment]
感谢大佬，解决问题

**Comment by Agnes4m** [comment]
顺便再提一个小建议，在搭配插件时[nonebot-plugin-miao](https://github.com/CMHopeSunshine/nonebot-plugin-miao)

数据库会记录带有口癖的内容，导致学习输出的时候会带双倍的口癖

**Comment by CMHopeSunshine** [comment]
这个没办法，不会考虑跨插件相关
