### ISSUE TITLE
提问：如何迁移学习数据

### ISSUE THREAD

**Issue by Agnes4m** [CMHopeSunshine/nonebot-plugin-learning-chat#35]
假如我想把一个bot学习的内容迁移到另外一个服务器的bot上，我通过复制data/learn_chat文件夹后,我从网页控制台发现正常读取了聊天记录和学习内容，但是原本所在的群聊内，没办法复现曾经几乎可以固定的回复。

也就算说，除了data/learn_chat外，还需有复制什么或者修改什么吗？

**Comment by CMHopeSunshine** [comment]
是图片内容吗，图片是用的协议端（go-cqhttp）的缓存，如果这些缓存数据没有一起转移的话，图片是发不出去的

**Comment by Agnes4m** [comment]
不仅仅是图片 ，文字也没有响应。

顺便问问，我应当复制gocqhttp的data中哪些部分，才能正常获取回复内容
