### ISSUE TITLE
转换消息[CQ:image,file=c2a8b9291bf34486071898d00c594a24.image]时出现错误：invalid image

### ISSUE THREAD

**Issue by 47Lux** [CMHopeSunshine/nonebot-plugin-learning-chat#37]
用-update-protocol的方法解决风控问题后，之前学习的图片就发不了了，发出来的全是[CQ:image,file=c2a8b9291bf34486071898d00c594a24.image]这种东西，学习到的文字倒是可以发出来

**Comment by CMHopeSunshine** [comment]
是否更换过gocq的位置或者删掉了它的文件呢，发图片是用gocq存的缓存，缓存没有了的话就是`invalid image`

**Comment by 47Lux** [comment]
> 是否更换过gocq的位置或者删掉了它的文件呢，发图片是用gocq存的缓存，缓存没有了的话就是`invalid image`

之前是把整个cq都重新弄了一遍，缓存应该是在这个过程中删除了？

**Comment by CMHopeSunshine** [comment]
缓存就是在go-cqhttp的data目录里
