### ISSUE TITLE
关于复读功能

### ISSUE THREAD

**Issue by fsqhn** [CMHopeSunshine/nonebot-plugin-learning-chat#38]
现在复读功能貌似是有概率是跟着复读，但有概率是会回复打断复读。
该如何配置才能保持一直是加入复读呢？

**Comment by CMHopeSunshine** [comment]
在Web UI 后台管理的分群配置中可以调整相关配置

**Comment by fsqhn** [comment]
看了下，Web UI 后台管理的分群配置中仅能调整复读阈值，但没办法选择复读阈值到达后是加入复读还是打断复读。

**Comment by CMHopeSunshine** [comment]
有一个配置叫打断复读概率啊，你把它改成0不就是了

**Comment by fsqhn** [comment]
![微信截图_20230606100451](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/assets/13745793/5521f771-5c35-492d-b47b-e9f42d5dc599)
绝了，我这并没有看到这个配置选项。但我刚更新完插件，是不是还要做点啥操作才能改啊。

**Comment by CMHopeSunshine** [comment]
方便截个图看看吗

**Comment by CMHopeSunshine** [comment]
看来是组件联动出问题了，把主动发言按钮打开才能看到打断复读按钮

**Comment by fsqhn** [comment]
十分感谢，已经修改了。
