### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by brightmoon2020** [CMHopeSunshine/nonebot-plugin-learning-chat#39]
有提示已连接学习连接库，但报错[ERROR] nonebot | Failed to import "nonebot_plugin_learning_chat"
web报错{"detail":"Not Found"}
![Uploading QQ图片20230608112941.png…]()

**Comment by CMHopeSunshine** [comment]
看不到你发的图片，能重新上传一下吗

**Comment by brightmoon2020** [comment]
> 看不到你发的图片，能重新上传一下吗

![QQ图片20230608112941](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/assets/51014585/005cd186-b4ac-46df-8c05-52b788e7ddf2)

**Comment by CMHopeSunshine** [comment]
请截全，有的的报错信息是在异常堆栈的最后几行

**Comment by brightmoon2020** [comment]
> 请截图，有用的报错信息在异常堆垛的最后几行

<img width="760" alt="微信截图_20230608114406" src="https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/assets/51014585/ec60ed94-8564-4ba5-b134-b80471d0761d">
<img width="778" alt="微信截图_20230608114649" src="https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/assets/51014585/d57da438-c51b-44f8-9058-a3c59b960d55">

**Comment by CMHopeSunshine** [comment]
可能是amis版本更新导致的，把版本降一下，(进入虚拟环境后)`pip install amis-python==1.0.7`

**Comment by 47Lux** [comment]
我也遇到了这个问题，请问解决了吗

**Comment by CMHopeSunshine** [comment]
升级到新版`0.2.3`试试

**Comment by PackageInstaller** [comment]
> 升级到新版`0.2.3`试试

我这边报错解决了，感谢
