### ISSUE TITLE
【启动报错】AttributeError : type object 'Item has no attribute 'ListBodyField!

### ISSUE THREAD

**Issue by Agnes4m** [CMHopeSunshine/nonebot-plugin-learning-chat#42]
pypi版本：1.3.0(nb脚手架安装)
python : 3.10.6
nb ： 2.0.0
系统： ubuntu22.04
![image](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/assets/70925546/9c022602-7167-45d9-9d45-4c549143e540)

**Comment by CMHopeSunshine** [comment]
更新`amis-python`至最新版
