### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by A7424** [CMHopeSunshine/nonebot-plugin-learning-chat#49]
![HHSUOION$UQ$%U W 9@$AWS](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/assets/103619507/f9151259-2b2a-42fb-a0a6-57b5bc9fc8cf)
插件版本为0.2.2
amis-python版本为1.0.7

**Comment by CMHopeSunshine** [comment]
你的配置文件变成None了，是不是手动修改过

**Comment by A7424** [comment]
> 你的配置文件变成None了，是不是手动修改过

尝试过重新安装插件，按理说是不会有变化的

**Comment by CMHopeSunshine** [comment]
重装插件并不会影响配置文件啊，你看看bot目录/data/learning_chat/learning_chat.yml文件内容是否正常

**Comment by A7424** [comment]
> 重装插件并不会影响配置文件啊，你看看bot目录/data/learning_chat/learning_chat.yml文件内容是否正常

文件内是空的，之前并没有碰过

**Comment by CMHopeSunshine** [comment]
把它删了，重启bot

**Comment by A7424** [comment]
> 把它删了，重启bot

已解决，感谢

**Comment by A7424** [comment]
> 把它删了，重启bot

目前可以正常启动，但会有不明原因的报错
![HHSUOION$UQ$%U W 9@$AWS](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/assets/103619507/c51941f1-1ba1-4cf1-870c-a4c4decce1a3)

**Comment by CMHopeSunshine** [comment]
您是不是把配置文件打开了没关闭导致不能正常保存，或者没有给python足够的权限保存文件啊，为啥配置文件会自己变成空文件呢

**Comment by A7424** [comment]
> 您是不是把配置文件打开了没关闭导致不能正常保存，或者没有给python足够的权限保存文件啊，为啥配置文件会自己变成空文件呢

刚看了一眼，配置文件是没问题的，也正常保存过
![LLN~8`3PR16D%B {(D$6Z}W](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/assets/103619507/1c27fe9c-d2e9-4fe8-ae94-2c32b29fe86d)

**Comment by CMHopeSunshine** [comment]
那再重启试试

**Comment by A7424** [comment]
> 那再重启试试

坏了，不能复现了
