### ISSUE TITLE
无法访问后台Web UI，报错ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by qingtian-crazy** [CMHopeSunshine/nonebot-plugin-learning-chat#54]
服务器：华为云Ubuntu22.04
nb机器人：ATRI
安装方式：ATRI自带的安装商店插件的功能
确认开启了web ui的功能
![image](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/assets/132991686/3dd2c965-9ccb-4050-bf91-5d6ae352a58d)
ATRI开启了相应的端口
![image](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/assets/132991686/3bf2a289-0032-4ef8-b763-94e4b56588cf)
输入地址为吗，马赛克是服务器ip
![image](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/assets/132991686/070f6979-a065-45b4-956f-6212e46822c1)
报错结果是ERR_CONNECTION_TIMED_OUT
在本地电脑ping了服务器没有问题
在nb机器人后台也没有看到什么报错

**Comment by qingtian-crazy** [comment]
服务器对应入方向端口也打开了
![image](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/assets/132991686/2309ed0e-ef06-4c44-a569-13a0ef5cffa0)

**Comment by CMHopeSunshine** [comment]
很明显并没有开放成功，非本插件问题，建议再检查linux内防火墙是否已开放

**Comment by CMHopeSunshine** [comment]
另外推荐使用反向代理服务器

**Comment by qingtian-crazy** [comment]
忘记回复了，后面查实确实是端口没有成功开放的问题，不好意思，感谢指导
