### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Shu-Ying** [CMHopeSunshine/nonebot-plugin-learning-chat#56]
很抱歉我不懂Python, 我尝试解决这个问题失败 只能来发布Issues

nonebot给我的日志为:

AttributeError:
"load()" has been removed, use

  yaml = YAML(typ='rt')
  yaml.load(...)

and register any classes that you use, or check the tag attribute on the loaded data,
instead of file "C:\Users\Administrator\Desktop\Bot\Diuse\src\plugins\nonebot_plugin_learning_chat\config.py", line 78

                yaml.load(

**Comment by CMHopeSunshine** [comment]
看来是依赖版本问题，试试 `pip install ruamel.yaml==0.17.21`，如果有使用虚拟环境那先激活虚拟环境

**Comment by Shu-Ying** [comment]
> 看来是依赖版本问题，试试`pip install ruamel.yaml==0.17.21`，如果有使用虚拟环境那先激活虚拟环境

我想我需要poke.txt的一个案例, 比如说文件内容 or 格式

**Comment by Shu-Ying** [comment]
> 看来是依赖版本问题，试试 `pip install ruamel.yaml==0.17.21`，如果有使用虚拟环境那先激活虚拟环境

是依赖版本问题, 问题已经得到解决. 感激不尽
