### ISSUE TITLE
希望数据库使用nonebot-plugin-tortoise-orm

### ISSUE THREAD

**Issue by yaowan233** [CMHopeSunshine/nonebot-plugin-learning-chat#6]
在[nonebot-plugin-osubot](https://github.com/yaowan233/nonebot-plugin-osubot)中使用了[nonebot-plugin-tortoise-orm](https://github.com/kexue-z/nonebot-plugin-tortoise-orm)作为了数据库的连接和使用
然后我这边有用户反馈nonebot-plugin-osubot的功能无法使用，数据库出了问题，经排查后发现他同时装了[nonebot-plugin-learning-chat](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat)与[nonebot-plugin-osubot](https://github.com/yaowan233/nonebot-plugin-osubot)
这两个插件都使用了tortoise-orm，如果分开来初始化会有问题，希望能不能统一一下都使用[nonebot-plugin-tortoise-orm](https://github.com/kexue-z/nonebot-plugin-tortoise-orm)，谢谢！

**Comment by CMHopeSunshine** [comment]
7472e1a2e0c33e75fb74afa50287f1dd78442ec9 0.1.1版本已经修复了，不会影响其他使用tortoise-orm的插件

**Comment by yaowan233** [comment]
ok
