### ISSUE TITLE
您好，请问如何不使用反代直接将Web控制台开放到公网

### ISSUE THREAD

**Issue by SunshineboyZj** [CMHopeSunshine/nonebot-plugin-learning-chat#61]

**Comment by SunshineboyZj** [comment]
一是服务器（Windows）配置有点紧张😂而且感觉为了反代这一个功能去下其它软件用不太着🙁

**Comment by CM-Edelweiss** [comment]
将`.env.*`里HOST改为`0.0.0.0`，防火墙放行nb的端口，就可以直接访问了
`http://服务器ip:nb端口/learning_chat/login`
