### ISSUE TITLE
WebUI login页面白屏

### ISSUE THREAD

**Issue by DD1605** [CMHopeSunshine/nonebot-plugin-learning-chat#63]
一开始部署完插件后可以正常访问webui，过了几天后访问webui login页面就是白屏了，尝试访问admin界面如下，然后跳转至白屏的login页面：
<img width="951" alt="{54E8DFF4-5E24-4731-B079-05EF9F24DCAE}" src="https://github.com/user-attachments/assets/c0d3d393-3dc1-4520-946e-fe6e6cb4c484">
<img width="462" alt="{B8C80652-6F4A-4C91-BCEB-9D5FDBB7D078}" src="https://github.com/user-attachments/assets/0524b64f-b92e-423a-bea7-2f7628b0d502">
<img width="959" alt="{14EA18FC-EBDB-4395-A617-38EE1D2252D5}" src="https://github.com/user-attachments/assets/186fee91-dd28-47a2-9dfc-22467978ced9">

**Comment by nikoyoke1** [comment]
同样遇到该问题

**Comment by MIKUKANO** [comment]
一样也遇到了

**Comment by lyh2421** [comment]
一样

**Comment by dascard** [comment]
一样

**Comment by wdsjjszr** [comment]
同样遇到该问题

**Comment by lyh2421** [comment]
求救

**Comment by CM-Edelweiss** [comment]
是 cdn挂了

**Comment by lyh2421** [comment]
> 是 cdn挂了

求解决

**Comment by CM-Edelweiss** [comment]
加上cdn='https://npm.onmicrosoft.cn',
![79f1dcb7ea9da81649fe294fed652a98](https://github.com/user-attachments/assets/3f09d728-86cb-424a-8fee-d97eecd57911)

**Comment by CM-Edelweiss** [comment]
> > 是 cdn挂了
> 
> 求解决
加上cdn='https://npm.onmicrosoft.cn',
![Uploading 79f1dcb7ea9da81649fe294fed652a98.png…]()

**Comment by CM-Edelweiss** [comment]
> > 是 cdn挂了
> 
> 求解决

web_api.py加上cdn='https://npm.onmicrosoft.cn/',
![79f1dcb7ea9da81649fe294fed652a98](https://github.com/user-attachments/assets/3246244b-6744-4e4f-a618-34a96f05d8e8)

**Comment by KaMmySuma** [comment]
> > > 是 cdn挂了
> > 
> > 
> > 求解决
> 
> web_api.py加上cdn='https://npm.onmicrosoft.cn/', ![79f1dcb7ea9da81649fe294fed652a98](https://private-user-images.githubusercontent.com/110460087/384607659-3246244b-6744-4e4f-a618-34a96f05d8e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMTQ5MzAsIm5iZiI6MTczMTIxNDYzMCwicGF0aCI6Ii8xMTA0NjAwODcvMzg0NjA3NjU5LTMyNDYyNDRiLTY3NDQtNGU0Zi1hNjE4LTM0YTk2ZjA1ZDhlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwNDU3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Mzc1ZjIwZTU2YTg3OTA4NWZlZWY1YmZlZjZkZjQ0ZmQwZWNkZTBhY2Y4ZDg0ZTliYTQ3ZTY0MGEyODI4MDllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0oOmvjq4FMsfO7Qbj-pBR561E_0sBmifQaoZGuxkd2U)

有效解决，感谢

**Comment by DreamGallery** [comment]
> web_api.py加上cdn='https://npm.onmicrosoft.cn/'

不知道为什么加上还是一片白色，换了好几个cdn也是一样的情况

**Comment by CM-Edelweiss** [comment]
> > web_api.py加上cdn='https://npm.onmicrosoft.cn/'
> 
> 不知道为什么加上还是一片白色，换了好几个cdn也是一样的情况
> 

换个浏览器试试

**Comment by zlqd123** [comment]
该文件位于
/usr/local/lib/python（换成你的版本号）/site-packages/nonebot_plugin_learning_chat/web_api.py
