### ISSUE TITLE
有个地址写错了

### ISSUE THREAD

**Issue by yaowan233** [CMHopeSunshine/nonebot-plugin-learning-chat#8]
https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/blob/7472e1a2e0c33e75fb74afa50287f1dd78442ec9/nonebot_plugin_learning_chat/web_api.py#L30
应该是/learning_chat/login

**Comment by CMHopeSunshine** [comment]
收到，感谢反馈

**Comment by CMHopeSunshine** [comment]
f231e93e1022f4a24fe9a876685e727e8efa8f9a 已修改
